- name: Check if swap is already enabled
  shell: swapon --summary
  changed_when: false
  register: swapon_summary

- name: Create swap file if not already enabled
  block:
    - name: Allocate swap file
      command: fallocate -l 4G /swapfile
      when: swapon_summary.stdout == ""

    - name: Secure swap file
      command: chmod 600 /swapfile
      when: swapon_summary.stdout == ""

    - name: Setup swap file
      command: mkswap /swapfile
      when: swapon_summary.stdout == ""

    - name: Enable swap file
      command: swapon /swapfile
      when: swapon_summary.stdout == ""

    - name: Add swap file to fstab
      lineinfile:
        path: /etc/fstab
        line: '/swapfile swap swap defaults 0 0'
        create: yes
      when: swapon_summary.stdout == ""
